function paths = paths_project(  )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
    paths = {
    '\AccumulatorElectricity',...
    '\AccumulatorHeat',...
    '\Biogas',...
    '\DataMaterials',...
    '\DataWeather',...
    '\Ground',...
    '\Orangery',...
    '\SolarBatteries',...
    '\SolarCollector',...
    '\SolarConcentrator',...
    '\WindTurbine',...
    '\_Research',...
    '\DATA'
    };

end

